name: WinfxkLib
main: cn.winfxk.nukkit.winfxklib.WinfxkLib
api:
  - 1.0.0
version: 2.0
load: STARTUP
website: http://Winfxk.cn
author: Winfxk
permissions:
  WinfxkLib.Command.Admin:
    description: 管理命令
    default: op
  WinfxkLib.Form.Item:
    description: 修改物品数据
    default: op