name: WinfxkLib
main: cn.winfxk.nukkit.winfxklib.WinfxkLib
api:
  - 1.0.0
version: 1.1.22.6.19.12.33
load: STARTUP
website: http://Winfxk.cn
author: Winfxk
permissions:
  WinfxkLib.Command.Admin:
    description: 管理命令
    default: op
  WinfxkLib.Form.Item:
    description: 修改物品数据
    default: op
  WinfxkLib.Command.Player:
    description: 玩家命令
    default: true
  WinfxkLib.use.LeaveWord:
    description: 留言面板权限
    default: true