Economy: EconomyAPI
BlacklistEconomy: [ ]
FormID: 4586545
FormIDBak: 465434
EconomyAPI-MoneyName: 金币
EasyEconomy:
  Name: 狗屎
  ID: EasyEconomy
物品列表页最大数量: 30
#每日留言限制
LeaveWordAstrict: 10
#如果玩家配置文件不存在，是否允许留言
UnrealLeaveWord: true